use std::collections::BTreeMap;

use crate::scanner::report::formatter::*;

/// Markdown report suitable for GitHub, GitLab, or documentation.
pub struct MarkdownFormatter;

impl OutputFormatter for MarkdownFormatter {
    fn format(&self, report: &Report) -> String {
        let mut out = String::new();

        // Title
        out.push_str("# Sentinel Security Report\n\n");

        if !report.summary.project_name.is_empty() {
            out.push_str(&format!("**Project:** {}\n\n", report.summary.project_name));
        }

        // Summary table
        out.push_str("## Summary\n\n");
        out.push_str("| Metric | Value |\n");
        out.push_str("|--------|-------|\n");
        out.push_str(&format!(
            "| Files Scanned | {} |\n",
            report.summary.total_files
        ));
        out.push_str(&format!(
            "| Rules Executed | {} |\n",
            report.summary.total_rules
        ));
        out.push_str(&format!(
            "| Findings | {} |\n",
            report.summary.total_findings
        ));
        if report.summary.suppressed_findings > 0 {
            out.push_str(&format!(
                "| Suppressed | {} |\n",
                report.summary.suppressed_findings
            ));
        }
        out.push_str(&format!(
            "| Security Score | **{}/100** |\n",
            report.score.score
        ));
        out.push_str(&format!(
            "| Duration | {}ms |\n",
            report.summary.duration.as_millis()
        ));
        out.push('\n');

        // Severity breakdown
        out.push_str("### Severity Breakdown\n\n");
        out.push_str("| Severity | Count |\n");
        out.push_str("|----------|-------|\n");
        out.push_str(&format!("| Critical | {} |\n", report.score.critical));
        out.push_str(&format!("| High | {} |\n", report.score.high));
        out.push_str(&format!("| Medium | {} |\n", report.score.medium));
        out.push_str(&format!("| Low | {} |\n", report.score.low));
        out.push_str(&format!("| Info | {} |\n", report.score.info));
        out.push('\n');

        // Findings
        let sorted = report.sorted_findings();
        if !sorted.is_empty() {
            out.push_str("## Findings\n\n");
            out.push_str("| Severity | Rule | File | Line | Column | Message |\n");
            out.push_str("|----------|------|------|------|--------|--------|\n");

            for finding in &sorted {
                let sev = finding.severity.as_str().to_uppercase();
                let fd = finding.span.file.display();
                let msg = escape_md(&finding.message);
                out.push_str(&format!(
                    "| {} | `{}` | `{}` | {} | {} | {} |\n",
                    sev, finding.rule_id, fd, finding.span.line, finding.span.column, msg,
                ));
            }
            out.push('\n');

            // Recommendations
            let mut recommendations: BTreeMap<String, Vec<String>> = BTreeMap::new();
            for finding in &sorted {
                let rid = finding.rule_id.to_string();
                recommendations
                    .entry(rid)
                    .or_default()
                    .push(finding.recommendation.clone());
            }

            out.push_str("## Recommendations\n\n");
            for (rule_id, recs) in &recommendations {
                out.push_str(&format!("### `{}`\n\n", rule_id));
                for rec in recs {
                    if !rec.is_empty() {
                        out.push_str(&format!("- {}\n", escape_md(rec)));
                    }
                }
                out.push('\n');
            }
        } else {
            out.push_str("No issues found.\n\n");
        }

        out.push_str("---\n");
        out.push_str(&format!(
            "*Report generated by Sentinel v{}*\n",
            env!("CARGO_PKG_VERSION")
        ));

        out
    }
}

fn escape_md(text: &str) -> String {
    text.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::{Category, DiagnosticSpan, RuleId, Severity};

    fn finding(
        severity: Severity,
        rule: &str,
        file: &str,
        line: usize,
        col: usize,
    ) -> crate::core::Finding {
        crate::core::Finding::new(
            RuleId::new(rule).unwrap(),
            severity,
            Category::Security,
            DiagnosticSpan::new(file, line, col),
            "test message",
            "test recommendation",
        )
    }

    fn caps() -> ReportOptions {
        ReportOptions {
            color: false,
            unicode: false,
            width: 80,
        }
    }

    fn summary(duration_ms: u64) -> ReportSummary {
        ReportSummary {
            project_name: "test-project".to_string(),
            total_files: 5,
            total_rules: 10,
            total_findings: 2,
            suppressed_findings: 0,
            duration: std::time::Duration::from_millis(duration_ms),
            parse_duration: std::time::Duration::from_millis(10),
            rule_duration: std::time::Duration::from_millis(40),
        }
    }

    fn report_data(findings: Vec<crate::core::Finding>, duration_ms: u64) -> Report {
        Report {
            score: crate::core::SecurityScore::from_findings(&findings),
            summary: summary(duration_ms),
            options: caps(),
            findings,
        }
    }

    #[test]
    fn markdown_title_and_project() {
        let formatter = MarkdownFormatter;
        let r = report_data(vec![], 0);
        let output = formatter.format(&r);
        assert!(output.starts_with("# Sentinel Security Report"));
        assert!(output.contains("**Project:** test-project"));
    }

    #[test]
    fn markdown_summary_table() {
        let formatter = MarkdownFormatter;
        let r = report_data(vec![], 50);
        let output = formatter.format(&r);
        assert!(output.contains("| Files Scanned | 5 |"));
        assert!(output.contains("| Rules Executed | 10 |"));
        assert!(output.contains("| Findings | 2 |"));
        assert!(output.contains("**100/100**"));
    }

    #[test]
    fn markdown_severity_breakdown() {
        let formatter = MarkdownFormatter;
        let r = report_data(vec![finding(Severity::Critical, "c", "f.rs", 1, 1)], 50);
        let output = formatter.format(&r);
        assert!(output.contains("### Severity Breakdown"));
        assert!(output.contains("| Critical | 1 |"));
        assert!(output.contains("| High | 0 |"));
    }

    #[test]
    fn markdown_findings_table() {
        let formatter = MarkdownFormatter;
        let r = report_data(
            vec![finding(Severity::High, "test-rule", "src/main.rs", 10, 3)],
            50,
        );
        let output = formatter.format(&r);
        assert!(output.contains("## Findings"));
        assert!(output.contains("| HIGH | `test-rule` | `src/main.rs` | 10 | 3 |"));
        assert!(output.contains("test message"));
    }

    #[test]
    fn markdown_recommendations_section() {
        let formatter = MarkdownFormatter;
        let r = report_data(
            vec![finding(Severity::Medium, "fix-rule", "f.rs", 5, 1)],
            50,
        );
        let output = formatter.format(&r);
        assert!(output.contains("## Recommendations"));
        assert!(output.contains("### `fix-rule`"));
        assert!(output.contains("test recommendation"));
    }

    #[test]
    fn markdown_empty_no_findings() {
        let formatter = MarkdownFormatter;
        let r = report_data(vec![], 0);
        let output = formatter.format(&r);
        assert!(output.contains("No issues found."));
        assert!(!output.contains("## Findings"));
    }

    #[test]
    fn markdown_ends_with_footer() {
        let formatter = MarkdownFormatter;
        let r = report_data(vec![], 0);
        let output = formatter.format(&r);
        assert!(output.contains("*Report generated by Sentinel"));
    }

    #[test]
    fn markdown_escapes_pipe_characters() {
        let formatter = MarkdownFormatter;
        let mut f = finding(Severity::Info, "pipe-rule", "f.rs", 1, 1);
        f.message = "contains | pipe".to_string();
        let r = report_data(vec![f], 0);
        let output = formatter.format(&r);
        assert!(output.contains("contains \\| pipe"));
    }

    #[test]
    fn markdown_suppressed_count_shown() {
        let formatter = MarkdownFormatter;
        let mut s = summary(50);
        s.suppressed_findings = 3;
        let r = Report {
            score: crate::core::SecurityScore::perfect(),
            summary: s,
            options: caps(),
            findings: vec![],
        };
        let output = formatter.format(&r);
        assert!(output.contains("| Suppressed | 3 |"));
    }
}
